# Generated by Django 5.0.6 on 2024-06-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publication',
            new_name='Article',
        ),
    ]
