# Generated by Django 5.0.6 on 2024-06-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_publication_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='publication',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='publication',
            new_name='article',
        ),
    ]
