# Generated by Django 5.0.6 on 2024-06-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_answerupvote_articlefavorite_articleupvote_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='answerupvote',
            constraint=models.UniqueConstraint(fields=('answer', 'user'), name='unique_answer_user_upvote'),
        ),
        migrations.AddConstraint(
            model_name='articleupvote',
            constraint=models.UniqueConstraint(fields=('article', 'user'), name='unique_article_user_upvote'),
        ),
        migrations.AddConstraint(
            model_name='commentupvote',
            constraint=models.UniqueConstraint(fields=('comment', 'user'), name='unique_comment_user_upvote'),
        ),
        migrations.AddConstraint(
            model_name='questionupvote',
            constraint=models.UniqueConstraint(fields=('question', 'user'), name='unique_question_user_upvote'),
        ),
    ]
